### ISSUE TITLE
[JENKINS-67005] Disable build status notification for multi branch pipelines 

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/github-branch-source-plugin#1380]
<p>Trying to skip build status notification at SCM for multi-branch pipeline jobs which uses  github repo and Bitbucket repos.</p>

<p>Job1: Bitbucket repo</p>

<p>Job2: Github Repo.</p>

<p>Installed Skip Notifications Trait plugin and added the resolveScm step in post  / always section to disable the build status notification at respective repos.</p>

<pre>
checkout resolveScm(source: github(repoOwner: <span class="code-quote">'Corp'</span>, repository: <span class="code-quote">'cicd'</span>, traits: [skipNotifications()]))
</pre>

<pre>
 checkout resolveScm(source: bitbucket(repoOwner: <span class="code-quote">'stdca'</span>, repository: <span class="code-quote">'cicd-automation'</span>, traits: [skipNotifications()]))
</pre>
<p>whereas I am getting error for both jobs</p>

<p> </p>

<pre>
java.lang.NullPointerException{{ at java.util.ArrayList.<init>(ArrayList.java:178)}}{{ at org.jenkinsci.plugins.workflow.multibranch.ResolveScmStep.<init>(ResolveScmStep.java:94)}}Caused: java.lang.reflect.InvocationTargetException
.....
Caused: java.lang.IllegalArgumentException: Could not instantiate {source=@​bitbucket(repoOwner=stdca,repository=cicd-automation.git,traits=[@​skipNotifications()])} <span class="code-keyword">for</span> org.jenkinsci.plugins.workflow.multibranch.ResolveScmStep
</pre>
<p> </p>

<p><span class="nobr"><a href="https://issues.jenkins.io/secure/attachment/56676/56676_bitbucket_repo_error.pdf" title="bitbucket_repo_error.pdf attached to JENKINS-67005">bitbucket_repo_error.pdf<sup><img class="rendericon" src="https://issues.jenkins.io/images/icons/link_attachment_7.gif" height="7" width="7" align="absmiddle" alt="" border="0"/></sup></a></span></p>

<p>For github repo also getting similar error. So Installed the plugin <a href="https://plugins.jenkins.io/disable-github-multibranch-status" class="external-link" target="_blank" rel="nofollow noopener">Disable GitHub Multibranch Status Plugin 1.2</a></p>

<p>But It disabled build status notifications for all Pull requests from github repo.</p>

<p>Use Case: Skip Build notifications for Branch builds and Pull request builds which have merge conflicts.</p>

<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=harasai">harasai</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-67005" target="_blank">Disable build status notification for multi branch pipelines </a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>component(s)</b>: github-branch-source-plugin, skip-notifications-trait-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-12-02
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Trying to skip build status notification at SCM for multi-branch pipeline jobs which uses  github repo and Bitbucket repos.</p>

<p>Job1: Bitbucket repo</p>

<p>Job2: Github Repo.</p>

<p>Installed Skip Notifications Trait plugin and added the resolveScm step in post  / always section to disable the build status notification at respective repos.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">checkout resolveScm(source: github(repoOwner: <span class="code-quote">'Corp'</span>, repository: <span class="code-quote">'cicd'</span>, traits: [skipNotifications()]))
</pre>
</div></div>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"> checkout resolveScm(source: bitbucket(repoOwner: <span class="code-quote">'stdca'</span>, repository: <span class="code-quote">'cicd-automation'</span>, traits: [skipNotifications()]))
</pre>
</div></div>
<p>whereas I am getting error for both jobs</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.NullPointerException{{ at java.util.ArrayList.&lt;init&gt;(ArrayList.java:178)}}{{ at org.jenkinsci.plugins.workflow.multibranch.ResolveScmStep.&lt;init&gt;(ResolveScmStep.java:94)}}Caused: java.lang.reflect.InvocationTargetException
.....
Caused: java.lang.IllegalArgumentException: Could not instantiate {source=@bitbucket(repoOwner=stdca,repository=cicd-automation.git,traits=[@skipNotifications()])} <span class="code-keyword">for</span> org.jenkinsci.plugins.workflow.multibranch.ResolveScmStep
</pre>
</div></div>
<p> </p>

<p><span class="nobr"><a href="https://issues.jenkins.io/secure/attachment/56676/56676_bitbucket_repo_error.pdf" title="bitbucket_repo_error.pdf attached to JENKINS-67005">bitbucket_repo_error.pdf<sup><img class="rendericon" src="https://issues.jenkins.io/images/icons/link_attachment_7.gif" height="7" width="7" align="absmiddle" alt="" border="0"/></sup></a></span></p>

<p>For github repo also getting similar error. So Installed the plugin <a href="https://plugins.jenkins.io/disable-github-multibranch-status" class="external-link" target="_blank" rel="nofollow noopener">Disable GitHub Multibranch Status Plugin 1.2</a></p>

<p>But It disabled build status notifications for all Pull requests from github repo.</p>

<p>Use Case: Skip Build notifications for Branch builds and Pull request builds which have merge conflicts.</p>

<p> </p>

<p> </p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 2.263.4<br/>
Skip Notifications Trait plugin 1.0.5<br/>
Bitbucket Branch Source 2.9.7<br/>
GitHub Branch Source Plugin 2.9.9<br/>
```
</details>
<details><summary><i>1 attachment</i></summary>

- [bitbucket_repo_error.pdf](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-last/refs/heads/main/attachments/56676/bitbucket_repo_error.pdf)
</details>

**Comment by jglick** [comment]
User error?
